# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rlt7-VoOrrZjgQ2zAFXeFu1925OO_pb8
"""

print("Welcome to weather prediction")
T=float(input("Enter temperature: "))
H=float(input("Enter humidity: "))
wind=float(input("Enter wind speed: "))
W=0.5*(T*T)-0.2*(H)+(0.1*wind)-15
if W>300:
    print("Prediction: Sunny")
elif W<=300 and W>200:
    print("Prediction: Cloudy")
elif W<=200 and W>100:
    print("Prediction: Rainy")
elif W<=100:
    print("Prediction: Stormy")
print(W)